### ISSUE TITLE
PXD-605 ⁃ Fail to submit experimental_metadata in kidsfirst qa

### ISSUE THREAD

**Issue by giangbui** [uc-cdis/sheepdog#144] opened 2018-06-05 16:43 UTC
Sheepdog consistently returns the indexd error when submitting experimental_metadata for acct projet in kidsfirst QA. ( There is no the did in indexd though)
"message": "400 Client Error: ('did \"36f73461-638c-4db3-9956-5b1e15dcffaf\" already exists!

**Comment by philloooo** [comment] 2018-06-05 16:45
this is not a bug but a feature for current sheepdog, current sheepdog doesn't allow duplicated nodes(nodes with the same md5sum) until https://github.com/uc-cdis/sheepdog/pull/137 is merged.

**Closed** 2018-07-18 21:10 UTC
Labels: bug
